name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - sympy
  - scipy
  - ffmpeg
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib